name: requirements_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=23.0.1
  - pip:
      - streamlit
      - numpy
      - pandas
      - PyMuPDF  # For PDF handling
      - torch      # For machine learning
      - transformer  # For NLP tasks
      - matplotlib # For plotting
      - seaborn   # For statistical data visualization
      - langchain  # For language processing
      - gradio   # For interactive UI components
      - ghostscript # For PDF handling
      - pymupdf  # For PDF handling
      - PyYAML    # For YAML parsing
      - tqdm     # For progress bars
      - joblib   # For parallelization
      - requests # For HTTP requests
      - certifi # For certificate handling
      - pillow   # For image processing
      - openai   # For GPT-3.5 API
      - tiktoken   # For tokenization  
      - gensim    # For word embeddings
      - spacy     # For NLP tasks
      - langchain # For language processing